version: '3.8'

services:
  consul:
    image: hashicorp/consul:latest
    command: agent -dev -client=0.0.0.0
    ports:
      - "8500:8500"

  auth-service:
    build: ./auth_service
    depends_on:
      - consul

  catalog-1:
    build: ./catalog_service
    environment:
      - INSTANCE_NAME=catalog-1
    depends_on:
      - consul

  catalog-2:
    build: ./catalog_service
    environment:
      - INSTANCE_NAME=catalog-2
    depends_on:
      - consul

  nginx:
    image: nginx:latest
    ports:
      - "80:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - auth-service
      - catalog-1
      - catalog-2