upstream catalog_backend {
    server catalog-1:8000;
    server catalog-2:8000;
}

server {
    listen 80;

    location /auth/ {
        proxy_pass http://auth-service:8000/;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
    }

    location /catalog/ {
        proxy_pass http://catalog_backend/;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
    }
}